[project]
name = "foundations-of-machine-teaching"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "feature-engine>=1.9.4",
    "imbalanced-learn>=0.14.1",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.8",
    "numpy>=2.4.3",
    "pandas>=3.0.1",
    "scikit-learn>=1.8.0",
    "seaborn>=0.13.2",
    "ucimlrepo>=0.0.7",
]
